### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by alantreadway** [PascalA94/GoT-Kill-List#1]
```
$ ng build
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/Users/alan/Downloads/tests/GoT-Kill-List/the-list-app/node_modules/@angular/cli/tasks/build.js:16:56)
    at Class.run (/Users/alan/Downloads/tests/GoT-Kill-List/the-list-app/node_modules/@angular/cli/commands/build.js:143:26)
    at Class.<anonymous> (/Users/alan/Downloads/tests/GoT-Kill-List/the-list-app/node_modules/@angular/cli/ember-cli/lib/models/command.
js:134:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Missing Angular config file?

**Comment by PascalA94** [comment]
Apologies, I have just uploaded three extra files, that I have only just realised were missing.  Hopefully this should sort the issue. Also, just so you are aware I have also used the latest version of the Angular Cli. Thank you for contacting me about this.
